name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on:
      - self-hosted
      - server2019
      - vs2019c
    steps:
      - uses: actions/checkout@v2
      - name: build debug library
        run:
          mkdir cmake-build-debug ;
          cd cmake-build-debug ;
          cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Debug ;
          cd .. ;
          mkdir debug-artifacts;
          move cmake-build-debug\Debug\clips.dll debug-artifacts  ;
          move cmake-build-debug\Debug\clipscli.exe debug-artifacts  ;
          cd debug-artifacts  ;
          dumpbin /dependents .\clipscli.exe  ;
      - name: build release library
        run:
          mkdir cmake-build-release ;
          cd cmake-build-release ;
          cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Release  ;
          cd .. ;
          mkdir release-artifacts;
          move cmake-build-debug\Debug\clips.dll release-artifacts  ;
          move cmake-build-debug\Debug\clipscli.exe release-artifacts  ;
          cd release-artifacts  ;
          dumpbin /dependents .\clipscli.exe  ;