name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on:
      - self-hosted
      - server2019
      - vs2019c
    steps:
      - name: build debug library
        run:
          mkdir cmake-build-debug ;
          cd cmake-build-debug ;
          cmake --config Debug -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Debug ;
      - name: build release library
        run:
          mkdir cmake-build-release ;
          cd cmake-build-release ;
          cmake --config Release -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Release  ;