name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on:
      - self-hosted
      - server2019
      - vs2019c
    steps:
      - uses: actions/checkout@v2
      - name: build static 6.31 release
        run:
          Remove-Item -LiteralPath "c:/usr" -Force -Recurse -ErrorAction Ignore ;
          mkdir cmake-build-static-631-release ;
          cd cmake-build-static-631-release ;
          cmake -Dbuild-631=ON -Dstatic-cli=ON  -DCMAKE_INSTALL_PREFIX=c:\usr  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Release  ;
          cmake --install . ;
          cd .. ;
          md -Force release-artifacts ;
          powershell -C  "&  Compress-Archive -Path C:\usr -DestinationPath release-artifacts\clips-static-631-$env:GITHUB_RUN_NUMBER.zip " ;
          cd release-artifacts  ;
          dumpbin /dependents C:/usr/bin/clipscli.exe  ;
      - name: build dynamic 6.31 release
        run:
          Remove-Item -LiteralPath "c:/usr" -Force -Recurse -ErrorAction Ignore ;
          mkdir cmake-build-dynamic-631-release ;
          cd cmake-build-dynamic-631-release ;
          cmake -Dbuild-631=ON -Dstatic-cli=OFF -DCMAKE_INSTALL_PREFIX=c:\usr  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Release  ;
          cmake --install . ;
          cd .. ;
          md -Force release-artifacts  ;
          powershell -C  "&  Compress-Archive -Path C:\usr -DestinationPath release-artifacts\clips-dynamic-631-$env:GITHUB_RUN_NUMBER.zip " ;
          cd release-artifacts  ;
          dumpbin /dependents C:/usr/bin/clipscli.exe  ;
      - name: build clipspy-0.3.3
        run:
          cd clipspy-0.3.3 ;
          python setup.py bdist_wheel ;
      - name: build static 6.40 release
        run:
          Remove-Item -LiteralPath "c:/usr" -Force -Recurse -ErrorAction Ignore ;
          mkdir cmake-build-static-640-release ;
          cd cmake-build-static-640-release ;
          cmake -Dstatic-cli=ON  -DCMAKE_INSTALL_PREFIX=c:\usr  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Release  ;
          ctest ; 
          cmake --install . ;
          cd .. ;
          md -Force release-artifacts  ;
          powershell -C  "&  Compress-Archive -Path C:\usr -DestinationPath release-artifacts\clips-static-640-$env:GITHUB_RUN_NUMBER.zip " ;
          cd release-artifacts  ;
          dumpbin /dependents C:/usr/bin/clipscli.exe  ;
      - name: build dynamic 6.40 release
        run:
          Remove-Item -LiteralPath "c:/usr" -Force -Recurse -ErrorAction Ignore ;
          mkdir cmake-build-dynamic-640-release ;
          cd cmake-build-dynamic-640-release ;
          cmake -Dstatic-cli=OFF -DCMAKE_INSTALL_PREFIX=c:\usr  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Release  ;
          ctest ; 
          cmake --install . ;
          cd .. ;
          md -Force release-artifacts  ;
          powershell -C  "&  Compress-Archive -Path C:\usr -DestinationPath release-artifacts\clips-dynamic-640-$env:GITHUB_RUN_NUMBER.zip " ;
          cd release-artifacts  ;
          dumpbin /dependents C:/usr/bin/clipscli.exe  ;
      - name: build clipspy-1.0.0
        run:
          cd clipspy-1.0.0 ;
          python setup.py bdist_wheel ;
          cd dist ;
          pip install --upgrade --force-reinstall *.whl ;
          cp c:\usr\bin\clips.dll c:\Python\Library\bin\clips.dll;
          python -c "import clips" ;
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: release-artifacts\
      - uses: actions/upload-artifact@v2
        with:
          name: clipspy-0.3.3-wheel
          path: clipspy-0.3.3/dist/*.whl
      - uses: actions/upload-artifact@v2
        with:
          name: clipspy-1.0.0-wheel
          path: clipspy-1.0.0/dist/*.whl
