name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on:
      - self-hosted
      - server2019
      - vs2019c
    steps:
      - uses: actions/checkout@v2
      - name: build debug library
        run:
          mkdir cmake-build-debug ;
          cd cmake-build-debug ;
          cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Debug ;
          cd .. ;
          mkdir debug-artifacts;
          move cmake-build-debug\Debug\clips.dll debug-artifacts  ;
          move cmake-build-debug\Debug\clipscli.exe debug-artifacts  ;
          cd debug-artifacts  ;
          dumpbin /dependents .\clipscli.exe  ;
      - name: build release library
        run:
          mkdir cmake-build-release ;
          cd cmake-build-release ;
          cmake -Dstatic-cli=ON  -DCMAKE_INSTALL_PREFIX=c:\usr  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True .. ;
          cmake --build . --target ALL_BUILD --config Release  ;
          cmake --install .
          cd .. ;
          mkdir release-artifacts;
          powershell -C  "&  Compress-Archive -Path C:\usr -DestinationPath release-artifacts\clips-$env:CI_COMMIT_SHORT_SHA.zip " ;
          cd release-artifacts  ;
          dumpbin /dependents C:/usr/bin/clipscli.exe  ;
      - name: build clipspy
        run:
          call c:\Python\condabin\activate.bat ;
          cd clipspy-0.3.3 ;
          python setup.py bdist_wheel ;
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: release-artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: clipspy-wheel
          path: clipspy-0.3.3/dist/*.whl
